title: 나의 포트폴리오
email: your@email.com
description: >-
  이것은 나의 포트폴리오 웹사이트입니다.
baseurl: ""
url: "https://junseokhub.github.io"

theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  pages:
    output: true
    permalink: /:title/
