title: 나의 포트폴리오
email: your@email.com
description: >-
  이것은 나의 포트폴리오 웹사이트입니다.
baseurl: ""  # GitHub Pages에서 /레포이름 형태로 쓸 경우 여기에 입력
url: "https://junseokhub.github.io"

theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

permalink: /:title/

sass:
  style: compressed
  load_paths:
    - _sass

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      css: "/assets/css/custom.css"
