export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Main } from "./Main";
export { default as Expertise } from "./Expertise";
export { default as Timeline } from "./Experience";
export { default as Competency } from "./Competency";
export { default as OpenSource } from "./OpenSource";
export { default as Contact } from "./Contact";
export { default as About } from "./About";
